[build-system]
requires = [
    "setuptools>=42,<72.2.0",
    "pybind11>=2.10.0"
]
build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
test-requires = "pytest"
test-command = "pytest {project}/tests"
